config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'home', to: 'pages#home'

  devise_for :users

  resources :job_listings

  resources :penguin

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job_listing.rb
class JobListing < ApplicationRecord

  belongs_to :user

  validates :position, presence: true
  validates :description, presence: true
  validates :salary, presence: true

end

app/models/penguin.rb
class Penguin < ApplicationRecord

  validates :head, presence: true
  validates :hand, presence: true
  validates :foot, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :job_listings

  validates :username, uniqueness: true, presence: true, length: { minimum: 3 }
  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password, :password_confirmation])
  end

end

app/controllers/job_listings_controller.rb
class JobListingsController < ApplicationController

  before_action :authenticate_user!

  def index
    @job_listings = JobListing.all
    @job_listing = JobListing.new
  end

  def show
    @job_listing = job_listing
  end

  def new
    @job_listing = JobListing.new
  end

  def create
    @job_listings = JobListing.all
    @job_listing = current_user.job_listings.build(job_listing_params)

    if @job_listing.save
      @job_listing = JobListing.new
    end
  end

  def edit
    @job_listing = job_listing
  end

  def update
    @job_listing = job_listing
    if @job_listing.update(job_listing_params)
      redirect_to job_listings_path
    else
      render :edit, flash: { error: 'Failed to update job listing' }
    end
  end

  def destroy
    @job_listings = JobListing.all
    @job_listing = job_listing
    @job_listing.destroy

    respond_to do |format|
      format.html { redirect_to job_listings_path }
      format.js
    end
  end

  private

  def job_listing
    JobListing.find(params[:id])
  end

  def job_listing_params
    params.require(:job_listing).permit(:position, :salary, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/penguins_controller.rb
class PenguinsController < ApplicationController

  def index
    @penguins = Penguin.all
  end

  def show
    @penguin = penguin
  end

  def new
    @penguin = Penguin.new
  end

  def create
    @penguin = Penguin.new(penguin_params)
    if @penguin.save
      redirect_to penguins_path
    else
      render :new
    end
  end

  def edit
    @penguin = penguin
  end

  def update
    @penguin = penguin
    if @penguin.update(penguin_params)
      redirect_to penguins_path
    else
      redirect_to penguins_path, flash[:error] = 'Failed to create penguin'
    end
  end

  def destroy
    @penguin = penguin
    @penguin.destroy
    redirect_to penguins_path
  end

  private

  def penguin
    Penguin.find(params[:id])
  end

  def penguin_params
    params.require(:penguin).permit(:head, :body, :foot)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_listings/_job_listings.html.erb
<table id='jtable' class='table table-striped table-hover'>

  <thead>
    <th></th>
    <th>Position</th>
    <th>Salary</th>
    <th>Description</th>
  </thead>

  <tbody>
    <%- @job_listings.each.with_index(1) do |job_listing, index| %>

      <tr>
        <td><%= index %></td>
        <td><%= job_listing.position %></td>
        <td><%= job_listing.salary %></td>
        <td><%= job_listing.description %></td>
        <td><%= link_to 'Delete', job_listing_path(job_listing), method: :delete, remote: true, class: 'btn btn-warning' %></td>
      </tr>

    <% end %>
  </tbody>

</table>

app/views/job_listings/_job_listings_form.html.erb
<%= simple_form_for @job_listing, url: job_listings_path, remote: true, method: :post, html: { id: 'job_listing_form' } do |form| %>

  <%= form.error_notification %>

  <%= form.input :position, label: false, placeholder: 'Position' %>
  <%= form.input :salary, label: false, placeholder: 'Salary' %>
  <%= form.input :description, label: false, placeholder: 'Description' %>

  <%= form.submit 'Save', class: 'btn btn-primary col-xs-8 col-xs-offset-2', data: { 'disable-with': "Saving..." } %>

<% end %>

app/views/job_listings/create.js.erb
$('#job_listing_form').html("<%= j render partial: 'job_listings_form' %>");

if("<%= @job_listing.errors.empty? %>") {
  $('#job_listings_table').html("<%= j render partial: 'job_listings' %>");
}

app/views/job_listings/destroy.js.erb
$('#job_listings_table').html("<%= j render partial: 'job_listings', job_listings: @job_listings %>");

app/views/job_listings/index.html.erb
<div class='container'>

  <div class='row'>

    <div class='col-md-6 col-md-offset-3'>

      <h1 class='text-center'>List a job here</h1>

      <div id='job_listings_form_container'>

        <%= render partial: 'job_listings_form' %>

      </div>

    </div>

  </div>

  <div class='row'>

    <div class='col-xs-12'>

      <div id='job_listings_table'>

        <%= render partial: 'job_listings' %>

      </div>

    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcProjectTemplate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container'>

  <div class='row'>
    <div class='col-xs-12'>
      <%= link_to 'Sign In', '#', class: 'btn btn-primary' %>
    </div>
  </div>

</div>